version: "3.5"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin_123
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - mysqlnetwork
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
    networks:
      - mysqlnetwork
    
networks:
  mysqlnetwork:
