version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - volmysql:/var/lib/mysql
    networks:
      - mysqlnetwork
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
    networks:
      - mysqlnetwork
    
networks:
  mysqlnetwork:

volumes:
  volmysql: