version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin_123
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    volumes:
      - volmysql:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - mynetwork
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql

networks:
  mynetwork:

volumes:
  volmysql: