version: "3.5"

services:
  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-container
   restart: always
   ports:
    - 5672:5672
    - 15672:15672
   volumes:
    - /var/lib/rabbitmq:/var/lib/rabbitmq
    - /var/log/rabbitmq:/var/log/rabbitmq
   networks:
    - rabbitmqnetwork

networks:
 rabbitmqnetwork:
  driver: bridge