version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin_123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /root/postgresql/data:/var/lib/postgresql/data
      # - /var/lib/postgresql/data:var/lib/postgresql/data