services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-container
    restart: always
    ports:
      - 1433:1433
    volumes:
      # - volsql:/var/lib/mssqlql/data
      - /root/sqlserver:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin_123
    networks:
      - sqlnetwork

networks:
  sqlnetwork:

# volumes:
#   volsql: