services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-container
    restart: always
    ports:
      - 1433:1433
    volumes:
      - /root/mssql/data:/var/lib/mssql/data
      # - /var/lib/mssql/data:/var/lib/mssql/data
      # for file backup
      # sudo chmod 777 /root/sqlserver
      # sudo a+r /root/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin_123