version: "3.5"

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb-container
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongod
        - MONGO_INITDB_ROOT_PASSWORD=Admin_123
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /root/mongodb/data/db:/data/db
      - /root/mongodb/dev.archive:/data/dev.archive
      - /root/production:/data/production
  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress-container
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=mongod
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=Admin_123
  #     - ME_CONFIG_MONGODB_URL=mongodb://mongod:Admin_123@mongo:27017/?authSource=admin
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin123
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"