version: "3"

services:
  redis:
    image: redislabs/redismod
    container_name: redis-container
    # restart: always
    environment:
      - REDIS_PASSWORD=Admin_123
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/data:/data
#     networks:
#       - redisnetwork
  
#   redisinsight:
#     image: redislabs/redisinsight:latest
#     ports:
#       - "8001:8001"
#     networks:
#       - redisnetwork

# networks:
#   redisnetwork: