version: "3.7"

services:
  redis:
    image: redislabs/redismod
    container_name: redis-container
    restart: always
    environment:
      - REDIS_PASSWORD=Admin_123
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis/data:/data